app:
  temp_dir: "/tmp"
  stats_prefix: "ffmpeg_stats"

tools:
  ffmpeg: "ffmpeg"
  ffprobe: "ffprobe"
  nnedi_weights: null
  dovi_tool: null
  hdr10plus_tool:
    path: "hdr10plus_tool"
    timeout_seconds: 300
    extract_args: null
    inject_args: null

logging:
  level: "info"
  show_timestamps: true
  colored_output: true

progress:
  update_interval_ms: 1000

analysis:
  crop_detection:
    enabled: true
    sample_count: 3
    sdr_crop_limit: 24
    hdr_crop_limit: 64
    min_pixel_change_percent: 1.0
  hdr_detection:
    enabled: true
    crf_adjustment: 2.0
  hdr:
    enabled: true
    crf_adjustment: 2.0
    bitrate_multiplier: 1.5
  dolby_vision:
    enabled: true
    preserve_profile_7: true
    target_profile: "8.1"
    require_dovi_tool: true
    auto_profile_conversion: true
    fallback_to_hdr10: true
    crf_adjustment: 2.0
    bitrate_multiplier: 1.5
    # Mode-specific VBV settings for optimal performance vs compliance balance
    vbv_crf_bufsize: 80000            # Relaxed VBV buffer for CRF mode (50% reduction for speed)
    vbv_crf_maxrate: 60000            # Relaxed VBV max rate for CRF mode (62% reduction for speed)
    vbv_abr_bufsize: 120000           # Tighter VBV buffer for ABR/CBR modes (25% reduction)
    vbv_abr_maxrate: 100000           # Tighter VBV max rate for ABR/CBR modes (37% reduction)
    profile_specific_adjustments: true
    rpu_extraction_mode: "lossless"
    profile_conversion: "none"
  hdr10_plus:
    enabled: true
    require_tool: true
    fallback_to_hdr10: true
    crf_adjustment: 2.0
    bitrate_multiplier: 1.5
    encoding_complexity: 1.0
    validate_curves: true
    metadata_source: "generate"
    processing_mode: "standard"

profiles:
  default:
    title: "Default Profile"
    base_crf: 23.0
    base_bitrate: 5000
    hdr_bitrate: 6000
    content_type: "film"
    x265_params:
      preset: "medium"

filters:
  deinterlace:
    primary_method: "nnedi"
    fallback_method: "yadif"
    nnedi_settings:
      field: "auto"
  denoise:
    filter: "hqdn3d"
    params: "1:1:2:2"
